create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  video_id text not null,
  author text not null default '익명',
  content text not null,
  client_id text not null default 'legacy',
  created_at timestamptz not null default now()
);

alter table public.comments
  add column if not exists client_id text not null default 'legacy';

create index if not exists comments_video_id_created_at_idx
  on public.comments (video_id, created_at desc);

grant usage on schema public to anon;
grant usage on schema public to authenticated;
grant select, insert on public.comments to anon;
grant select, insert on public.comments to authenticated;

alter table public.comments enable row level security;

drop policy if exists "Allow public read comments" on public.comments;
create policy "Allow public read comments"
  on public.comments
  for select
  using (true);

drop policy if exists "Allow public insert comments" on public.comments;
create policy "Allow public insert comments"
  on public.comments
  for insert
  with check (true);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'comments'
  ) then
    alter publication supabase_realtime add table public.comments;
  end if;
end
$$;
