create table if not exists public.video_trend_runs (
  id bigint generated by default as identity primary key,
  region_code text not null,
  category_id text not null,
  category_label text not null,
  source_category_ids text[] not null default '{}',
  source text not null default 'youtube-mostPopular',
  captured_at timestamptz not null default now()
);

create index if not exists video_trend_runs_region_category_captured_at_idx
  on public.video_trend_runs (region_code, category_id, captured_at desc, id desc);

create table if not exists public.video_trend_snapshots (
  id bigint generated by default as identity primary key,
  run_id bigint not null references public.video_trend_runs (id) on delete cascade,
  region_code text not null,
  category_id text not null,
  video_id text not null,
  rank integer not null check (rank > 0),
  title text not null,
  channel_title text not null,
  thumbnail_url text not null,
  view_count bigint,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  unique (run_id, video_id)
);

create index if not exists video_trend_snapshots_region_category_video_idx
  on public.video_trend_snapshots (region_code, category_id, video_id, run_id desc);

create table if not exists public.video_trend_signals (
  region_code text not null,
  category_id text not null,
  video_id text not null,
  category_label text not null,
  current_run_id bigint not null references public.video_trend_runs (id) on delete cascade,
  previous_run_id bigint references public.video_trend_runs (id) on delete set null,
  current_rank integer not null check (current_rank > 0),
  previous_rank integer,
  rank_change integer,
  current_view_count bigint,
  previous_view_count bigint,
  view_count_delta bigint,
  sync_buy_count integer not null default 0 check (sync_buy_count >= 0),
  sync_buy_quantity bigint not null default 0 check (sync_buy_quantity >= 0),
  sync_sell_count integer not null default 0 check (sync_sell_count >= 0),
  sync_sell_quantity bigint not null default 0 check (sync_sell_quantity >= 0),
  is_new boolean not null default false,
  title text not null,
  channel_title text not null,
  thumbnail_url text not null,
  captured_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (region_code, category_id, video_id)
);

create index if not exists video_trend_signals_region_category_rank_idx
  on public.video_trend_signals (region_code, category_id, current_rank asc);

grant usage on schema public to anon;
grant usage on schema public to authenticated;
grant usage on schema public to service_role;
grant select, insert, update, delete on public.video_trend_runs to service_role;
grant select, insert, update, delete on public.video_trend_snapshots to service_role;
grant select on public.video_trend_signals to anon;
grant select on public.video_trend_signals to authenticated;
grant select, insert, update, delete on public.video_trend_signals to service_role;
grant usage, select on sequence public.video_trend_runs_id_seq to service_role;
grant usage, select on sequence public.video_trend_snapshots_id_seq to service_role;

alter table public.video_trend_signals enable row level security;

drop policy if exists "Allow public read trend signals" on public.video_trend_signals;
create policy "Allow public read trend signals"
  on public.video_trend_signals
  for select
  using (true);
