const countryCodes = [
  { code: 'AU', name: '호주' },
  { code: 'AT', name: '오스트리아' },
  { code: 'BE', name: '벨기에' },
  { code: 'CA', name: '캐나다' },
  { code: 'CL', name: '칠레' },
  { code: 'CO', name: '콜롬비아' },
  { code: 'CZ', name: '체코' },
  { code: 'DK', name: '덴마크' },
  { code: 'EE', name: '에스토니아' },
  { code: 'FI', name: '핀란드' },
  { code: 'FR', name: '프랑스' },
  { code: 'DE', name: '독일' },
  { code: 'GR', name: '그리스' },
  { code: 'HU', name: '헝가리' },
  { code: 'IS', name: '아이슬란드' },
  { code: 'IE', name: '아일랜드' },
  { code: 'IL', name: '이스라엘' },
  { code: 'IT', name: '이탈리아' },
  { code: 'JP', name: '일본' },
  { code: 'KR', name: '대한민국' },
  { code: 'LV', name: '라트비아' },
  { code: 'LT', name: '리투아니아' },
  { code: 'LU', name: '룩셈부르크' },
  { code: 'MX', name: '멕시코' },
  { code: 'NL', name: '네덜란드' },
  { code: 'NZ', name: '뉴질랜드' },
  { code: 'NO', name: '노르웨이' },
  { code: 'PL', name: '폴란드' },
  { code: 'PT', name: '포르투갈' },
  { code: 'SK', name: '슬로바키아' },
  { code: 'SI', name: '슬로베니아' },
  { code: 'ES', name: '스페인' },
  { code: 'SE', name: '스웨덴' },
  { code: 'CH', name: '스위스' },
  { code: 'TR', name: '터키' },
  { code: 'GB', name: '영국' },
  { code: 'US', name: '미국' },
] as const;

export default countryCodes;
