create extension if not exists pg_cron;
create extension if not exists pg_net;

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users (id) on delete cascade,
  email text not null unique,
  display_name text not null,
  picture_url text,
  is_admin boolean not null default false,
  created_at timestamptz not null default now(),
  last_login_at timestamptz not null default now()
);

create index if not exists profiles_last_login_at_idx
  on public.profiles (last_login_at desc);

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (
    auth_user_id,
    email,
    display_name,
    picture_url,
    last_login_at
  )
  values (
    new.id,
    coalesce(new.email, new.id::text || '@unknown.local'),
    coalesce(
      nullif(new.raw_user_meta_data ->> 'full_name', ''),
      nullif(new.raw_user_meta_data ->> 'name', ''),
      split_part(coalesce(new.email, '사용자'), '@', 1)
    ),
    coalesce(
      nullif(new.raw_user_meta_data ->> 'avatar_url', ''),
      nullif(new.raw_user_meta_data ->> 'picture', '')
    ),
    now()
  )
  on conflict (auth_user_id) do update
  set
    email = excluded.email,
    display_name = excluded.display_name,
    picture_url = excluded.picture_url,
    last_login_at = excluded.last_login_at;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert or update of email, raw_user_meta_data on auth.users
for each row
execute function public.handle_new_auth_user();

insert into public.profiles (
  auth_user_id,
  email,
  display_name,
  picture_url,
  created_at,
  last_login_at
)
select
  users.id,
  coalesce(users.email, users.id::text || '@unknown.local'),
  coalesce(
    nullif(users.raw_user_meta_data ->> 'full_name', ''),
    nullif(users.raw_user_meta_data ->> 'name', ''),
    split_part(coalesce(users.email, '사용자'), '@', 1)
  ),
  coalesce(
    nullif(users.raw_user_meta_data ->> 'avatar_url', ''),
    nullif(users.raw_user_meta_data ->> 'picture', '')
  ),
  users.created_at,
  coalesce(users.last_sign_in_at, users.created_at)
from auth.users
on conflict (auth_user_id) do nothing;

create table if not exists public.favorite_streamers (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.profiles (id) on delete cascade,
  channel_id text not null,
  channel_title text not null,
  thumbnail_url text,
  created_at timestamptz not null default now(),
  unique (user_id, channel_id)
);

create index if not exists favorite_streamers_user_created_at_idx
  on public.favorite_streamers (user_id, created_at desc);

create table if not exists public.playback_progress (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.profiles (id) on delete cascade,
  video_id text not null,
  video_title text,
  channel_title text,
  thumbnail_url text,
  position_seconds integer not null default 0 check (position_seconds >= 0),
  updated_at timestamptz not null default now(),
  unique (user_id, video_id)
);

create index if not exists playback_progress_user_updated_at_idx
  on public.playback_progress (user_id, updated_at desc);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  video_id text not null default 'global',
  author text not null default '익명',
  content text not null,
  client_id text not null default 'legacy',
  created_at timestamptz not null default now()
);

alter table public.comments
  add column if not exists user_id bigint references public.profiles (id) on delete set null,
  add column if not exists region_code text,
  add column if not exists message_type text not null default 'USER',
  add column if not exists system_event_type text;

create index if not exists comments_region_created_at_idx
  on public.comments (region_code, created_at desc);

create index if not exists comments_user_created_at_idx
  on public.comments (user_id, created_at desc);

create or replace function public.normalize_comment_content(raw_content text)
returns text
language sql
immutable
as $$
  select regexp_replace(trim(coalesce(raw_content, '')), '\s+', ' ', 'g');
$$;

create or replace function public.enforce_comment_spam_protection()
returns trigger
language plpgsql
as $$
declare
  latest_created_at timestamptz;
  normalized_content text;
  seconds_since_latest numeric;
  retry_after_seconds integer;
begin
  normalized_content := public.normalize_comment_content(new.content);
  new.content := normalized_content;

  if normalized_content = '' then
    raise exception using errcode = 'P0001', message = 'comment_content_required';
  end if;

  select comments.created_at
  into latest_created_at
  from public.comments
  where comments.client_id = new.client_id
    and coalesce(comments.region_code, '') = coalesce(new.region_code, '')
  order by comments.created_at desc
  limit 1;

  if latest_created_at is not null then
    seconds_since_latest := extract(epoch from (now() - latest_created_at));

    if seconds_since_latest < 5 then
      retry_after_seconds := greatest(1, ceil(5 - seconds_since_latest)::integer);
      raise exception using
        errcode = 'P0001',
        message = 'comment_spam_cooldown',
        detail = format('retry_after_seconds=%s', retry_after_seconds);
    end if;
  end if;

  if exists (
    select 1
    from public.comments
    where comments.client_id = new.client_id
      and coalesce(comments.region_code, '') = coalesce(new.region_code, '')
      and comments.created_at > now() - interval '30 seconds'
      and public.normalize_comment_content(comments.content) = normalized_content
  ) then
    raise exception using errcode = 'P0001', message = 'comment_spam_duplicate';
  end if;

  return new;
end;
$$;

drop trigger if exists comments_spam_protection on public.comments;
create trigger comments_spam_protection
before insert on public.comments
for each row
execute function public.enforce_comment_spam_protection();

create table if not exists public.video_trend_runs (
  id bigint generated by default as identity primary key,
  region_code text not null,
  category_id text not null,
  category_label text not null,
  source_category_ids text[] not null default '{}',
  source text not null default 'youtube-mostPopular',
  captured_at timestamptz not null default now()
);

create index if not exists video_trend_runs_region_category_captured_at_idx
  on public.video_trend_runs (region_code, category_id, captured_at desc, id desc);

create table if not exists public.video_trend_snapshots (
  id bigint generated by default as identity primary key,
  run_id bigint not null references public.video_trend_runs (id) on delete cascade,
  region_code text not null,
  category_id text not null,
  video_id text not null,
  rank integer not null check (rank > 0),
  title text not null,
  channel_title text not null,
  thumbnail_url text not null,
  view_count bigint,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  unique (run_id, video_id)
);

alter table public.video_trend_snapshots
  add column if not exists channel_id text,
  add column if not exists video_category_id text,
  add column if not exists video_category_label text,
  add column if not exists duration text;

create index if not exists video_trend_snapshots_region_category_video_idx
  on public.video_trend_snapshots (region_code, category_id, video_id, run_id desc);

create index if not exists video_trend_snapshots_created_at_idx
  on public.video_trend_snapshots (created_at);

create table if not exists public.video_trend_signals (
  region_code text not null,
  category_id text not null,
  video_id text not null,
  category_label text not null,
  current_run_id bigint not null references public.video_trend_runs (id) on delete cascade,
  previous_run_id bigint references public.video_trend_runs (id) on delete set null,
  current_rank integer not null check (current_rank > 0),
  previous_rank integer,
  rank_change integer,
  current_view_count bigint,
  previous_view_count bigint,
  view_count_delta bigint,
  is_new boolean not null default false,
  title text not null,
  channel_title text not null,
  thumbnail_url text not null,
  captured_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (region_code, category_id, video_id)
);

alter table public.video_trend_signals
  add column if not exists channel_id text,
  add column if not exists video_category_id text,
  add column if not exists video_category_label text,
  add column if not exists duration text;

create index if not exists video_trend_signals_region_category_rank_idx
  on public.video_trend_signals (region_code, category_id, current_rank asc);

create table if not exists public.game_seasons (
  id bigint generated by default as identity primary key,
  name text not null,
  status text not null default 'ACTIVE' check (status in ('SCHEDULED', 'ACTIVE', 'CLOSED')),
  region_code text not null,
  starting_balance_points bigint not null default 10000000 check (starting_balance_points >= 0),
  min_hold_seconds integer not null default 60 check (min_hold_seconds >= 0),
  max_open_positions integer not null default 5 check (max_open_positions > 0),
  rank_point_multiplier integer not null default 100 check (rank_point_multiplier > 0),
  start_at timestamptz not null default now(),
  end_at timestamptz not null default (now() + interval '7 days'),
  created_at timestamptz not null default now()
);

create unique index if not exists game_seasons_one_active_per_region_idx
  on public.game_seasons (region_code)
  where status = 'ACTIVE';

create index if not exists game_seasons_region_start_idx
  on public.game_seasons (region_code, start_at desc);

create table if not exists public.game_season_tiers (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.game_seasons (id) on delete cascade,
  tier_code text not null,
  display_name text not null,
  min_score bigint not null,
  badge_code text not null,
  title_code text not null,
  profile_theme_code text not null,
  inventory_slots integer not null,
  sort_order integer not null,
  created_at timestamptz not null default now(),
  unique (season_id, tier_code),
  unique (season_id, sort_order)
);

create table if not exists public.game_wallets (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.game_seasons (id) on delete cascade,
  user_id bigint not null references public.profiles (id) on delete cascade,
  balance_points bigint not null,
  reserved_points bigint not null default 0,
  realized_pnl_points bigint not null default 0,
  manual_tier_score_adjustment bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (season_id, user_id)
);

create table if not exists public.game_positions (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.game_seasons (id) on delete cascade,
  user_id bigint not null references public.profiles (id) on delete cascade,
  region_code text not null,
  category_id text not null,
  video_id text not null,
  title text not null,
  channel_title text not null,
  thumbnail_url text,
  buy_rank integer not null,
  sell_rank integer,
  quantity bigint not null check (quantity > 0),
  stake_points bigint not null check (stake_points >= 0),
  buy_captured_at timestamptz not null,
  status text not null default 'OPEN' check (status in ('OPEN', 'CLOSED')),
  created_at timestamptz not null default now(),
  closed_at timestamptz,
  origin_position_id bigint references public.game_positions (id) on delete set null
);

create index if not exists game_positions_user_season_status_idx
  on public.game_positions (user_id, season_id, status, created_at desc);

create index if not exists game_positions_video_status_idx
  on public.game_positions (region_code, video_id, status);

create table if not exists public.game_ledger (
  id bigint generated by default as identity primary key,
  wallet_id bigint not null references public.game_wallets (id) on delete cascade,
  position_id bigint references public.game_positions (id) on delete set null,
  ledger_type text not null,
  amount_points bigint not null,
  balance_after_points bigint not null,
  description text,
  created_at timestamptz not null default now()
);

create index if not exists game_ledger_wallet_created_idx
  on public.game_ledger (wallet_id, created_at desc);

create table if not exists public.game_scheduled_sell_orders (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.profiles (id) on delete cascade,
  season_id bigint not null references public.game_seasons (id) on delete cascade,
  position_id bigint not null references public.game_positions (id) on delete cascade,
  region_code text not null,
  trigger_type text not null default 'RANK' check (trigger_type in ('RANK', 'PROFIT_RATE')),
  target_rank integer,
  target_profit_rate_percent double precision,
  trigger_direction text not null default 'RANK_IMPROVES_TO'
    check (trigger_direction in ('RANK_IMPROVES_TO', 'RANK_DROPS_TO')),
  quantity bigint not null check (quantity > 0),
  status text not null default 'PENDING' check (status in ('PENDING', 'EXECUTED', 'CANCELED', 'FAILED')),
  sell_price_points bigint,
  settled_points bigint,
  pnl_points bigint,
  failure_reason text,
  triggered_at timestamptz,
  executed_at timestamptz,
  canceled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists game_scheduled_orders_pending_idx
  on public.game_scheduled_sell_orders (status, region_code, created_at)
  where status = 'PENDING';

create table if not exists public.game_notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.profiles (id) on delete cascade,
  season_id bigint references public.game_seasons (id) on delete cascade,
  position_id bigint references public.game_positions (id) on delete set null,
  region_code text not null,
  event_type text not null,
  notification_type text not null,
  title text not null,
  message text not null,
  video_id text,
  video_title text,
  channel_title text,
  thumbnail_url text,
  strategy_tags text[] not null default '{}',
  highlight_score bigint,
  title_code text,
  title_display_name text,
  title_grade text,
  show_modal boolean not null default false,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists game_notifications_user_region_created_idx
  on public.game_notifications (user_id, region_code, created_at desc);

create table if not exists public.game_highlights (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.profiles (id) on delete cascade,
  season_id bigint not null references public.game_seasons (id) on delete cascade,
  position_id bigint not null references public.game_positions (id) on delete cascade,
  region_code text not null,
  highlight_type text not null,
  title text not null,
  description text not null,
  highlight_rank integer,
  profit_points bigint,
  profit_rate_percent double precision,
  strategy_tags text[] not null default '{}',
  highlight_score bigint not null default 0,
  status text not null default 'ACTIVE',
  created_at timestamptz not null default now()
);

create index if not exists game_highlights_user_season_score_idx
  on public.game_highlights (user_id, season_id, highlight_score desc);

create table if not exists public.achievement_titles (
  code text primary key,
  display_name text not null,
  short_name text not null,
  grade text not null check (grade in ('NORMAL', 'RARE', 'SUPER', 'ULTIMATE')),
  description text not null,
  sort_order integer not null
);

insert into public.achievement_titles (code, display_name, short_name, grade, description, sort_order)
values
  ('bronze-investor', '브론즈 투자자', '브론즈', 'NORMAL', 'YouTube Atlas 게임을 시작했습니다.', 1),
  ('silver-investor', '실버 투자자', '실버', 'NORMAL', '실버 티어에 도달했습니다.', 2),
  ('gold-investor', '골드 투자자', '골드', 'RARE', '골드 티어에 도달했습니다.', 3),
  ('platinum-investor', '플래티넘 투자자', '플래티넘', 'RARE', '플래티넘 티어에 도달했습니다.', 4),
  ('diamond-investor', '다이아몬드 투자자', '다이아', 'SUPER', '다이아몬드 티어에 도달했습니다.', 5),
  ('master-investor', '마스터 투자자', '마스터', 'SUPER', '마스터 티어에 도달했습니다.', 6),
  ('legend-investor', '레전드 투자자', '레전드', 'ULTIMATE', '레전드 티어에 도달했습니다.', 7)
on conflict (code) do update
set
  display_name = excluded.display_name,
  short_name = excluded.short_name,
  grade = excluded.grade,
  description = excluded.description,
  sort_order = excluded.sort_order;

create table if not exists public.user_achievement_titles (
  user_id bigint not null references public.profiles (id) on delete cascade,
  title_code text not null references public.achievement_titles (code) on delete cascade,
  earned_at timestamptz not null default now(),
  primary key (user_id, title_code)
);

create table if not exists public.user_achievement_title_settings (
  user_id bigint primary key references public.profiles (id) on delete cascade,
  selected_title_code text references public.achievement_titles (code) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.game_season_results (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.profiles (id) on delete cascade,
  season_id bigint not null references public.game_seasons (id) on delete cascade,
  final_rank integer not null,
  final_asset_points bigint not null,
  final_balance_points bigint not null,
  realized_pnl_points bigint not null,
  final_highlight_score bigint not null default 0,
  final_tier_code text,
  final_tier_name text,
  final_tier_badge_code text,
  final_tier_title_code text,
  position_count integer not null default 0,
  title_code text,
  summary jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (user_id, season_id)
);

create or replace function public.seed_game_tiers(target_season_id bigint)
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.game_season_tiers (
    season_id,
    tier_code,
    display_name,
    min_score,
    badge_code,
    title_code,
    profile_theme_code,
    inventory_slots,
    sort_order
  )
  values
    (target_season_id, 'BRONZE', '브론즈', 0, 'season-bronze', 'bronze-investor', 'bronze', 5, 1),
    (target_season_id, 'SILVER', '실버', 5000, 'season-silver', 'silver-investor', 'silver', 7, 2),
    (target_season_id, 'GOLD', '골드', 15000, 'season-gold', 'gold-investor', 'gold', 10, 3),
    (target_season_id, 'PLATINUM', '플래티넘', 60000, 'season-platinum', 'platinum-investor', 'platinum', 12, 4),
    (target_season_id, 'DIAMOND', '다이아몬드', 300000, 'season-diamond', 'diamond-investor', 'diamond', 15, 5),
    (target_season_id, 'MASTER', '마스터', 1800000, 'season-master', 'master-investor', 'master', 17, 6),
    (target_season_id, 'LEGEND', '레전드', 12600000, 'season-legend', 'legend-investor', 'legend', 20, 7)
  on conflict (season_id, tier_code) do nothing;
$$;

create or replace function public.atlas_buy_position(
  target_user_id bigint,
  target_season_id bigint,
  target_region_code text,
  target_category_id text,
  target_video_id text,
  target_title text,
  target_channel_title text,
  target_thumbnail_url text,
  target_buy_rank integer,
  target_buy_captured_at timestamptz,
  target_stake_points bigint,
  target_quantity bigint
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  target_wallet public.game_wallets%rowtype;
  target_season public.game_seasons%rowtype;
  open_position_count integer;
  created_position_id bigint;
begin
  if target_stake_points <= 0 or target_quantity <= 0 then
    raise exception using errcode = 'P0001', message = 'invalid_trade_quantity';
  end if;

  select *
  into target_season
  from public.game_seasons
  where id = target_season_id and status = 'ACTIVE'
  for update;

  if not found then
    raise exception using errcode = 'P0001', message = 'active_season_not_found';
  end if;

  insert into public.game_wallets (season_id, user_id, balance_points)
  values (target_season.id, target_user_id, target_season.starting_balance_points)
  on conflict (season_id, user_id) do nothing;

  select *
  into target_wallet
  from public.game_wallets
  where season_id = target_season.id and user_id = target_user_id
  for update;

  if target_wallet.balance_points < target_stake_points then
    raise exception using errcode = 'P0001', message = 'insufficient_balance';
  end if;

  select count(*)
  into open_position_count
  from public.game_positions
  where season_id = target_season.id
    and user_id = target_user_id
    and status = 'OPEN';

  if open_position_count >= target_season.max_open_positions then
    raise exception using errcode = 'P0001', message = 'inventory_full';
  end if;

  update public.game_wallets
  set
    balance_points = balance_points - target_stake_points,
    updated_at = now()
  where id = target_wallet.id;

  insert into public.game_positions (
    season_id,
    user_id,
    region_code,
    category_id,
    video_id,
    title,
    channel_title,
    thumbnail_url,
    buy_rank,
    quantity,
    stake_points,
    buy_captured_at
  )
  values (
    target_season.id,
    target_user_id,
    upper(target_region_code),
    target_category_id,
    target_video_id,
    target_title,
    target_channel_title,
    target_thumbnail_url,
    target_buy_rank,
    target_quantity,
    target_stake_points,
    target_buy_captured_at
  )
  returning id into created_position_id;

  insert into public.game_ledger (
    wallet_id,
    position_id,
    ledger_type,
    amount_points,
    balance_after_points,
    description
  )
  values (
    target_wallet.id,
    created_position_id,
    'BUY',
    -target_stake_points,
    target_wallet.balance_points - target_stake_points,
    target_video_id
  );

  return created_position_id;
end;
$$;

create or replace function public.atlas_sell_position(
  target_user_id bigint,
  target_position_id bigint,
  target_quantity bigint,
  target_sell_rank integer,
  target_unit_price_points bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  target_position public.game_positions%rowtype;
  target_wallet public.game_wallets%rowtype;
  sold_stake_points bigint;
  sell_price_points bigint;
  sell_fee_points bigint;
  settled_points bigint;
  pnl_points bigint;
  next_balance bigint;
  sold_at timestamptz := now();
begin
  select *
  into target_position
  from public.game_positions
  where id = target_position_id
    and user_id = target_user_id
    and status = 'OPEN'
  for update;

  if not found then
    raise exception using errcode = 'P0001', message = 'position_not_found';
  end if;

  if target_quantity <= 0 or target_quantity > target_position.quantity then
    raise exception using errcode = 'P0001', message = 'invalid_trade_quantity';
  end if;

  if sold_at < target_position.created_at + (
    select make_interval(secs => min_hold_seconds)
    from public.game_seasons
    where id = target_position.season_id
  ) then
    raise exception using errcode = 'P0001', message = 'minimum_hold_not_reached';
  end if;

  select *
  into target_wallet
  from public.game_wallets
  where season_id = target_position.season_id
    and user_id = target_user_id
  for update;

  sold_stake_points := round(
    target_position.stake_points::numeric * target_quantity::numeric / target_position.quantity::numeric
  )::bigint;
  sell_price_points := round(
    greatest(0, target_unit_price_points)::numeric * target_quantity::numeric / 100::numeric
  )::bigint;
  sell_fee_points := floor(greatest(0, sell_price_points)::numeric * 3::numeric / 1000::numeric)::bigint;
  settled_points := greatest(0, sell_price_points - sell_fee_points);
  pnl_points := settled_points - sold_stake_points;
  next_balance := target_wallet.balance_points + settled_points;

  if target_quantity = target_position.quantity then
    update public.game_positions
    set
      status = 'CLOSED',
      sell_rank = target_sell_rank,
      closed_at = sold_at
    where id = target_position.id;
  else
    update public.game_positions
    set
      quantity = quantity - target_quantity,
      stake_points = stake_points - sold_stake_points
    where id = target_position.id;

    insert into public.game_positions (
      season_id,
      user_id,
      region_code,
      category_id,
      video_id,
      title,
      channel_title,
      thumbnail_url,
      buy_rank,
      sell_rank,
      quantity,
      stake_points,
      buy_captured_at,
      status,
      created_at,
      closed_at,
      origin_position_id
    )
    values (
      target_position.season_id,
      target_position.user_id,
      target_position.region_code,
      target_position.category_id,
      target_position.video_id,
      target_position.title,
      target_position.channel_title,
      target_position.thumbnail_url,
      target_position.buy_rank,
      target_sell_rank,
      target_quantity,
      sold_stake_points,
      target_position.buy_captured_at,
      'CLOSED',
      target_position.created_at,
      sold_at,
      target_position.id
    );
  end if;

  update public.game_wallets
  set
    balance_points = next_balance,
    realized_pnl_points = realized_pnl_points + pnl_points,
    updated_at = sold_at
  where id = target_wallet.id;

  update public.game_scheduled_sell_orders
  set
    status = 'CANCELED',
    canceled_at = sold_at,
    updated_at = sold_at
  where position_id = target_position.id
    and status = 'PENDING'
    and target_quantity = target_position.quantity;

  insert into public.game_ledger (
    wallet_id,
    position_id,
    ledger_type,
    amount_points,
    balance_after_points,
    description
  )
  values (
    target_wallet.id,
    target_position.id,
    'SELL',
    settled_points,
    next_balance,
    target_position.video_id
  );

  return jsonb_build_object(
    'positionId', target_position.id,
    'videoId', target_position.video_id,
    'buyRank', target_position.buy_rank,
    'sellRank', target_sell_rank,
    'rankDiff', target_position.buy_rank - target_sell_rank,
    'quantity', target_quantity,
    'stakePoints', sold_stake_points,
    'sellPricePoints', sell_price_points,
    'pnlPoints', pnl_points,
    'settledPoints', settled_points,
    'highlightScore', greatest(0, (target_position.buy_rank - target_sell_rank) * 100),
    'balancePoints', next_balance,
    'soldAt', sold_at
  );
end;
$$;

create or replace function public.delete_expired_atlas_data()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  deleted_runs bigint;
  deleted_comments bigint;
begin
  delete from public.video_trend_runs
  where captured_at < now() - interval '7 days';
  get diagnostics deleted_runs = row_count;

  delete from public.comments
  where created_at < now() - interval '30 days';
  get diagnostics deleted_comments = row_count;

  return jsonb_build_object(
    'deletedTrendRuns', deleted_runs,
    'deletedComments', deleted_comments,
    'deletedAt', now()
  );
end;
$$;

alter table public.profiles enable row level security;
alter table public.favorite_streamers enable row level security;
alter table public.playback_progress enable row level security;
alter table public.comments enable row level security;
alter table public.video_trend_runs enable row level security;
alter table public.video_trend_snapshots enable row level security;
alter table public.video_trend_signals enable row level security;
alter table public.game_seasons enable row level security;
alter table public.game_season_tiers enable row level security;
alter table public.game_wallets enable row level security;
alter table public.game_positions enable row level security;
alter table public.game_ledger enable row level security;
alter table public.game_scheduled_sell_orders enable row level security;
alter table public.game_notifications enable row level security;
alter table public.game_highlights enable row level security;
alter table public.achievement_titles enable row level security;
alter table public.user_achievement_titles enable row level security;
alter table public.user_achievement_title_settings enable row level security;
alter table public.game_season_results enable row level security;

drop policy if exists "Public profiles are readable" on public.profiles;
drop policy if exists "Users read own profile" on public.profiles;
create policy "Users read own profile"
  on public.profiles for select
  to authenticated
  using (auth.uid() = auth_user_id);

drop policy if exists "Users update own profile" on public.profiles;
create policy "Users update own profile"
  on public.profiles for update
  using (auth.uid() = auth_user_id)
  with check (auth.uid() = auth_user_id);

drop policy if exists "Users manage own favorites" on public.favorite_streamers;
create policy "Users manage own favorites"
  on public.favorite_streamers for all
  using (
    user_id = (select id from public.profiles where auth_user_id = auth.uid())
  )
  with check (
    user_id = (select id from public.profiles where auth_user_id = auth.uid())
  );

drop policy if exists "Users manage own playback" on public.playback_progress;
create policy "Users manage own playback"
  on public.playback_progress for all
  using (
    user_id = (select id from public.profiles where auth_user_id = auth.uid())
  )
  with check (
    user_id = (select id from public.profiles where auth_user_id = auth.uid())
  );

drop policy if exists "Allow public read comments" on public.comments;
drop policy if exists "Allow public insert comments" on public.comments;
drop policy if exists "Public comments are readable" on public.comments;
create policy "Public comments are readable"
  on public.comments for select
  using (true);

drop policy if exists "Authenticated users create comments" on public.comments;
create policy "Authenticated users create comments"
  on public.comments for insert
  to authenticated
  with check (
    user_id = (select id from public.profiles where auth_user_id = auth.uid())
  );

drop policy if exists "Public trend signals are readable" on public.video_trend_signals;
create policy "Public trend signals are readable"
  on public.video_trend_signals for select
  using (true);

drop policy if exists "Public active seasons are readable" on public.game_seasons;
create policy "Public active seasons are readable"
  on public.game_seasons for select
  using (true);

drop policy if exists "Public tiers are readable" on public.game_season_tiers;
create policy "Public tiers are readable"
  on public.game_season_tiers for select
  using (true);

drop policy if exists "Public titles are readable" on public.achievement_titles;
create policy "Public titles are readable"
  on public.achievement_titles for select
  using (true);

drop policy if exists "Users read own wallet" on public.game_wallets;
create policy "Users read own wallet"
  on public.game_wallets for select
  using (
    user_id = (select id from public.profiles where auth_user_id = auth.uid())
  );

drop policy if exists "Users read own positions" on public.game_positions;
create policy "Users read own positions"
  on public.game_positions for select
  using (
    user_id = (select id from public.profiles where auth_user_id = auth.uid())
  );

drop policy if exists "Users read own scheduled orders" on public.game_scheduled_sell_orders;
create policy "Users read own scheduled orders"
  on public.game_scheduled_sell_orders for select
  using (
    user_id = (select id from public.profiles where auth_user_id = auth.uid())
  );

drop policy if exists "Users read own notifications" on public.game_notifications;
create policy "Users read own notifications"
  on public.game_notifications for select
  using (
    user_id = (select id from public.profiles where auth_user_id = auth.uid())
  );

drop policy if exists "Users read own highlights" on public.game_highlights;
create policy "Users read own highlights"
  on public.game_highlights for select
  using (
    user_id = (select id from public.profiles where auth_user_id = auth.uid())
  );

drop policy if exists "Users read own earned titles" on public.user_achievement_titles;
create policy "Users read own earned titles"
  on public.user_achievement_titles for select
  using (
    user_id = (select id from public.profiles where auth_user_id = auth.uid())
  );

drop policy if exists "Users manage own selected title" on public.user_achievement_title_settings;
create policy "Users manage own selected title"
  on public.user_achievement_title_settings for all
  using (
    user_id = (select id from public.profiles where auth_user_id = auth.uid())
  )
  with check (
    user_id = (select id from public.profiles where auth_user_id = auth.uid())
  );

drop policy if exists "Users read own season results" on public.game_season_results;
create policy "Users read own season results"
  on public.game_season_results for select
  using (
    user_id = (select id from public.profiles where auth_user_id = auth.uid())
  );

grant usage on schema public to anon, authenticated, service_role;
revoke all on public.profiles from anon;
grant select, update on public.profiles to authenticated;
grant select, insert, update, delete on public.favorite_streamers to authenticated;
grant select, insert, update, delete on public.playback_progress to authenticated;
revoke insert on public.comments from anon;
grant select on public.comments to anon, authenticated;
grant insert on public.comments to authenticated;
grant select on public.video_trend_signals to anon, authenticated;
grant select on public.game_seasons, public.game_season_tiers, public.achievement_titles to anon, authenticated;
grant select on public.game_wallets, public.game_positions, public.game_scheduled_sell_orders,
  public.game_notifications, public.game_highlights, public.user_achievement_titles,
  public.user_achievement_title_settings, public.game_season_results to authenticated;
grant insert, update, delete on public.user_achievement_title_settings to authenticated;
grant all on all tables in schema public to service_role;
grant all on all sequences in schema public to service_role;
revoke all on function public.seed_game_tiers(bigint) from public, anon, authenticated;
revoke all on function public.atlas_buy_position(
  bigint, bigint, text, text, text, text, text, text, integer, timestamptz, bigint, bigint
) from public, anon, authenticated;
revoke all on function public.atlas_sell_position(
  bigint, bigint, bigint, integer, bigint
) from public, anon, authenticated;
revoke all on function public.delete_expired_atlas_data() from public, anon, authenticated;
grant execute on function public.seed_game_tiers(bigint) to service_role;
grant execute on function public.atlas_buy_position(
  bigint, bigint, text, text, text, text, text, text, integer, timestamptz, bigint, bigint
) to service_role;
grant execute on function public.atlas_sell_position(
  bigint, bigint, bigint, integer, bigint
) to service_role;
grant execute on function public.delete_expired_atlas_data() to service_role;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'comments'
  ) then
    alter publication supabase_realtime add table public.comments;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'game_notifications'
  ) then
    alter publication supabase_realtime add table public.game_notifications;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'game_positions'
  ) then
    alter publication supabase_realtime add table public.game_positions;
  end if;
end
$$;
